### ISSUE TITLE
Registro de entregas

### ISSUE THREAD

**Issue by henrique-zw** [henrique-zw/Trabalho_1_GCS#2]
- [x] O sistema deverá permitir registrar uma nova entrega, com data e hora, descrição e
apartamento de destino, bem como o operador que recebeu a entrega. Sugere-se gerar um ID
numérico sequencial a cada nova entrega.

- [x] O sistema deverá permitir ao operador registrar a retirada de uma entrega por um morador.

- [x] Registrar data e hora, o morador que retirou, relacionando com qual entrega já registrada
anteriormente.

**Comment by MattOliveir** [comment]
Vou Criar uma Branch pra fazer a remoção e o relacionamento.

**Comment by MattOliveir** [comment]
alguem pega a pull request e faz o merge pelo amor de jeová
