### ISSUE TITLE
Gerar o relatório final que será entregue ao professor

### ISSUE THREAD

**Issue by lucaslgm** [henrique-zw/Trabalho_1_GCS#22]
Relatório deve ser concluído até as 23h do dia 26.

- [x] Folha de rosto com nomes completos dos componentes do time.

- [x]  Link para o repositório público no GitHub

- [x] Descrição clara do fluxo de trabalho adotado (pode ser uma variação dos fluxos vistos
em aula, adaptado pelo time).

- [x]  Demonstração de que o time seguiu o fluxo definido. Deve conter capturas de tela e
descrições que deixem isto claro. (sugere-se capturar o Network graph do GitHub:
Insights/Network)

- [x] Tabela com os nomes dos componentes do grupo e suas contribuições (pode ser links
para commits ou pull-requests registrados no GitHub).

- [x] Conclusão contendo reflexões sobre as dificuldades encontradas, como foram superadas
e quais as lições aprendidas.

**Comment by Gatherytha** [comment]
Estou tendo um pouco de dificuldade em descrever o fluxo. Caso alguém possa colaborar, eu agradeço.
