### ISSUE TITLE
Lista de moradores

### ISSUE THREAD

**Issue by henrique-zw** [henrique-zw/Trabalho_1_GCS#3]
- [x] O sistema deverá manter uma lista de moradores (nome, RG e nro do apartamento).

- [x] O sistema deverá permitir incluir um novo morador (não é necessário implementar edição nem
exclusão).

- [x] Deverá ser possível listar todos os moradores do prédio.

- [x] implementar metodos no menu de interação

- [x] validar inputs

**Comment by lucaslgm** [comment]
Métodos de adição e listagem de moradores criados.
Talvez tenha que realizar algumas validações nos métodos mais adiante.

**Comment by lucaslgm** [comment]
Necessário implementar métodos no menu principal da classe App

**Comment by lucaslgm** [comment]
Done.
