### ISSUE TITLE
Procurar entregas

### ISSUE THREAD

**Issue by henrique-zw** [henrique-zw/Trabalho_1_GCS#5]
- [x] Deverá ser possível procurar entregas pela descrição.

- [x]  Poder listar todas as encontradas.

**Comment by Gatherytha** [comment]
- [x] Resolver bug de verificação. Atualmente, o código apresenta um problema na linha 103 da classe ListaEntregas, devido ao fato de que no sistema ainda não existe nenhum elemento na lista de Entregas retiradas. 

- [x] Bugs corrigidos.
