### ISSUE TITLE
Gerar relatório

### ISSUE THREAD

**Issue by henrique-zw** [henrique-zw/Trabalho_1_GCS#7]
- [x] Deverá ser possível gerar um relatório como o exemplo abaixo, entre uma data inicial e uma
data final escolhidas pelo operador (note que há entregas ainda não retiradas):
![image](https://user-images.githubusercontent.com/62674070/96326796-1d2ae580-100a-11eb-979a-27df38f1b2a1.png)

**Comment by lucaslgm** [comment]
Done.
